config/routes.rb
require 'logged_in_constraint'

Rails.application.routes.draw do

  get 'callback'  => 'sessions#callback'
  delete 'logout' => 'sessions#destroy'

  get 'main/view'
  get 'main/download'

  get 'groups/index' => 'groups#index', as: :group_index
  get 'groups/download/:id' => 'groups#download', as: :group_download

  get 'download_process' => 'groups#download_process', as: :download_process
  
  root to: 'main#index', constraints: LoggedInConstraint.new  
  root to: 'sessions#new', as: :unauth
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	# Delay between requests to VK API. Too frequent requests prohibited for small apps
	# REQUEST_DELAY = 0.2

	#@is_view
	#@groups
	#@user
	#@vkgg

	def index
		#byebug
		#@is_view = true
		#@user = vkgg.get_user_json(session[:vk_id])

		#load_group
		#view_internal
		redirect_to action: :view, format: :js
	end

  def view
		view_internal
  end

  def download
  	@is_view = false
  	@user = vkgg.get_user_json(session[:vk_id])	
  	@groups = vkgg.get_current_user_groups_json
  	#render 'main/index'
  end

  private

  def vkgg
  	@vk ||= VkHelper::VkGroupGrabber.new(session[:token])
	end

	def view_internal
    Delayed::Job.enqueue GetUserJob.new(session[:token], session[:vk_id])
    #@user = vkgg.get_user_json(session[:vk_id])

		#load_group
	end

  def view_internal_prev
    @user = vkgg.get_user_json(session[:vk_id])
    load_group
  end

	def load_group
		group = Vgroup.last
		@wall_posts = group.posts.order(:created_at)
		@empty_wall = @wall_posts.count == 0

		@discussions = group.topics.order(:created_at)
		@empty_topics = @discussions.count == 0
	end


end

app/helpers/main_helper.rb
module MainHelper
	def vk_url(user)
    #byebug
    "http://vk.com/#{user.screen_name}"
  end
end

app/views/main/_download.html.haml
.row
  .col-md-12
    %h2 Скачивание содержимого групп

.row
  .col-md-12
    = render 'groups'

app/views/main/_groups.html.haml
%table.table
  - if @groups.empty?
    %tr
      %td Вы не состоите в группах
  - else
    - @groups.each do |group|
      %tr
        %td
          = link_to image_tag(group.photo_50), vk_url(group), target: '_blank'
        %td.wide
          %i.icon-comment
          = link_to group.name, vk_url(group), target: '_blank'
        %td
          -#= link_to group_download_url(group.id), { class: ["download","btn", "btn-warning", "btn-xs"] } do
          = link_to group_download_path(group.id), { class: ["download","btn", "btn-primary", "btn-xs"] } do
            Скачать

        -#
          %button{ class: ["download","btn", "btn-warning", "btn-xs"], 
            "data-toggle": "modal", 
            "data-target": "#downloadModal",
            "data-groupname": "#{group.name}" } Скачать

/ Modal Not used by the moment
#downloadModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title Группа: 
      .modal-body
        -#= render 'downloadprogress'
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Закрыть
        -# %button.btn.btn-primary{:type => "button"} Save changes

app/views/main/_view.html.haml
.tabs
  %ul.nav.nav-pills.nav-justified
    %li.active
      %a{:href => '#tab-wall', 'data-toggle' => 'tab'} Стена
    %li
      %a{:href => '#tab-discussions', 'data-toggle' => 'tab'} Обсуждения

  .tab-content
    .tab-pane.fade.in.active#tab-wall
      = render 'view_wall'
    .tab-pane.fade#tab-discussions
      = render 'view_topics'

app/views/main/_view_topics.html.haml
.topics-header
  = "В группе тем: #{@discussions.count}" if !@empty_topics
%table.table
  - if @empty_topics
    %tr
      %td Обсуждений нет
  - else
    - @discussions.each do |topic|
      %tr
        %td
          = topic.json['title']
        %td Автор темы

app/views/main/_view_wall.html.haml
%table.table
  - if @empty_wall
    %tr
      %td Стена пуста
  - else
    - @wall_posts.each do |post|
      %tr
        %td
          = post.json['text']

app/views/main/download.js.haml
$('#working-area').html('#{ j render("download") }');
$('#link-view').toggleClass('active', false);
$('#link-download').toggleClass('active', true);

app/views/main/index.html.haml
.row.header
  .col-md-1
    = link_to root_path, class: "btn btn-default"do
      %i.glyphicon.glyphicon-home
  .col-md-11.text-right
    .h1 VK Grabber
.row.main-content
  .col-md-3
    .sidebar-nav
      %div{:class => ['navbar', 'navbar-default'], :role => 'navigation'}
        .navbar-header
          %button{ :class => "navbar-toggle", :type => "button", "data-toggle" => "collapse", "data-target" => ".sidebar-navbar-collapse" }
            %span{ :class => "sr-only" } Toggle navigation
            %span{ :class => "icon-bar" }
            %span{ :class => "icon-bar" }
          %span{:class => "visible-xs navbar-brand"} Sidebar menu
        %div{ :class => ["navbar-collapse", "collapse", "sidebar-navbar-collapse"] } 
          %ul{ :class => ["nav", "navbar-nav"]}
            %li{ :id => 'link-view', :class => ('active' if @is_view) }
              = link_to "Просмотреть", {:controller => 'main', :action => 'view'}, :remote => true, data: { no_turbolink: true }
            %li{ :id => 'link-download', :class => ('active' unless @is_view) }
              = link_to "Скачать", {:controller => 'main', :action => 'download'}, :remote => true, data: { no_turbolink: true }
              
  .col-md-9
    #working-area
      - if @is_view
        = render 'view'
      - else
        = render 'download'


  #longActionModal.modal.fade{"aria-labelledby" => "longActionModal", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
      .modal-content
        .alert.alert-danger
          %span.glyphicon.glyphicon-hourglass{'aria-hidden' => 'true'}
          Подождите...

app/views/main/view.js.haml
$('#working-area').html('#{ j render("view") }');
$('#link-view').toggleClass('active', true);
$('#link-download').toggleClass('active', false);