config/routes.rb
require 'logged_in_constraint'

Rails.application.routes.draw do

  get 'callback'  => 'sessions#callback'
  delete 'logout' => 'sessions#destroy'

  get 'main/view'
  get 'main/download'

  get 'groups/index' => 'groups#index', as: :group_index
  get 'groups/download/:id' => 'groups#download', as: :group_download

  get 'download_process' => 'groups#download_process', as: :download_process
  
  root to: 'main#index', constraints: LoggedInConstraint.new  
  root to: 'sessions#new', as: :unauth
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	def index
	end

	def download_process
    @job = Delayed::Job.enqueue DownloadJob.new(session[:group_id].to_i, session[:token]), :queue => 'vkgrabber'
    #@job = Delayed::Job.enqueue DownloadJob.new(1, 2), :queue => 'vkgrabber'
  end

  def download
  	group_id = params[:id].to_i
  	session[:group_id] = params[:id]

  	#byebug
  	groups = vkgg.get_current_user_groups_json
  	@group = groups.select{ |group| group.id == group_id }.first
  	#download_process(group_id)
  	#byebug
  	#vkgg.purgeDatabase
  	#vkgg.logGroup(group_id) unless group_id.nil?
  end

  private 
    def vkgg
  		VkHelper::VkGroupGrabber.new(session[:token])
  	end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_downloadprogress.html.haml
%div
	%h4.group-name 
		= @group.name
.export
	= link_to 'Начать скачивание', download_process_path, remote: true, class: 'btn btn-primary btn-lg'
	.well
		.row
			.col-xs-12
				.progress-stage.text-primary
		.row
			.col-xs-12
				.progress-substage.text-primary
		.row
			.col-xs-12
				.progress-status.text-primary
					0/0
		.row
			.col-xs-12
				.progress.progress-striped.active
					.progress-bar
						.text-primary
							0%
	= link_to 'View csv', "#{Rails.root}/export.csv", class: 'btn btn-success export-link', style: 'display:none'

app/views/groups/download.html.haml
= render 'downloadprogress'

app/views/groups/download_process.js.haml
:plain
  var interval;
  interval = setInterval(function(){
    $.ajax({
      url: '/progress-job/' + #{@job.id},
      success: function(job){
        var stage, progress;
        console.log('success start');
        // If there are errors
        if (job.last_error != null) {
          console.log('job-error:' + job.last_error);
          $('.progress-status').addClass('text-danger').text(job.progress_stage);
          $('.progress-bar').addClass('progress-bar-danger');
          $('.progress').removeClass('active');
          clearInterval(interval);
        }

        progress = job.progress_current / job.progress_max * 100;
        progress = progress.toFixed(2)
        // In job stage
        if (progress.toString() !== 'NaN'){
          //$('.progress-stage').addClass('text-danger').text(job.progress_stage.stage_name);
          //$('.progress-substage').addClass('text-danger').text(job.progress_stage.substage_name);
          $('.progress-stage').addClass('text-danger').text(JSON.parse(job.progress_stage).stage_name);
          $('.progress-substage').addClass('text-danger').text(JSON.parse(job.progress_stage).substage_name);
          $('.progress-status').text(job.progress_current + '/' + job.progress_max);
          $('.progress-bar').css('width', progress + '%').text(progress + '%');
        }
      },
      error: function(){
        console.log('error start');
        // Job is no loger in database which means it finished successfuly
        $('.progress').removeClass('active');
        $('.progress-bar').css('width', '100%').text('100%');
        $('.progress-status').text('Скачивание завершено успешно!');
        $('.export-link').show();
        console.log('error interval:' + interval);
        clearInterval(interval);
        console.log('error end');
      }
    })
  },200);
console.log('outer interval:'+interval);

app/views/groups/index.html.haml
= render 'downloadprogress'